{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fastapipoc.serviceAccountName" . }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
{{ include "fastapipoc.labels" . | nindent 4 }}
{{- end -}}
