name: Docker build and push image

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    name: Create Tag
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_REPO_GH_PAT }}
          DEFAULT_BUMP: minor
          WITH_V: true
          RELEASE_BRANCHES: .*

  build:
    needs: [create_tag]
    name: "Build"
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: brunoevonah
      TAG: ${{ needs.create_tag.outputs.new_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TAG }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.13

      - name: Poetry Install
        run: poetry install

      - name: Lint
        run: |
          poetry run flake8
          poetry run black --check .

      - name: Test
        run: poetry run pytest tests

      - name: Docker build
        run: docker build -t fastapipoc:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: brunoevonah
          password: ${{ secrets.DOCKER_PASS }}

      - name: Docker push
        run: |
          docker tag fastapipoc:latest ${{ env.DOCKER_REPO }}/fastapipoc:latest
          docker tag fastapipoc:latest ${{ env.DOCKER_REPO }}/fastapipoc:${{ env.TAG }}
          docker push ${{ env.DOCKER_REPO }}/fastapipoc:latest
          docker push ${{ env.DOCKER_REPO }}/fastapipoc:${{ env.TAG }}
